//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wirecard.DeveloperPortal.Core.SendInformationSMSService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MAuthToken", Namespace="http://services.mikro-odeme.com/")]
    [System.SerializableAttribute()]
    public partial class MAuthToken : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PinField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserCode {
            get {
                return this.UserCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserCodeField, value) != true)) {
                    this.UserCodeField = value;
                    this.RaisePropertyChanged("UserCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pin {
            get {
                return this.PinField;
            }
            set {
                if ((object.ReferenceEquals(this.PinField, value) != true)) {
                    this.PinField = value;
                    this.RaisePropertyChanged("Pin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MSendSMSInput", Namespace="http://services.mikro-odeme.com/")]
    [System.SerializableAttribute()]
    public partial class MSendSMSInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GsmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        private int RequestGsmOperatorField;
        
        private int RequestGsmTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Gsm {
            get {
                return this.GsmField;
            }
            set {
                if ((object.ReferenceEquals(this.GsmField, value) != true)) {
                    this.GsmField = value;
                    this.RaisePropertyChanged("Gsm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int RequestGsmOperator {
            get {
                return this.RequestGsmOperatorField;
            }
            set {
                if ((this.RequestGsmOperatorField.Equals(value) != true)) {
                    this.RequestGsmOperatorField = value;
                    this.RaisePropertyChanged("RequestGsmOperator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int RequestGsmType {
            get {
                return this.RequestGsmTypeField;
            }
            set {
                if ((this.RequestGsmTypeField.Equals(value) != true)) {
                    this.RequestGsmTypeField = value;
                    this.RaisePropertyChanged("RequestGsmType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MSendSMSOutput", Namespace="http://services.mikro-odeme.com/")]
    [System.SerializableAttribute()]
    public partial class MSendSMSOutput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid SendSMSObjectIdField;
        
        private int StatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        private int GsmOperatorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid SendSMSObjectId {
            get {
                return this.SendSMSObjectIdField;
            }
            set {
                if ((this.SendSMSObjectIdField.Equals(value) != true)) {
                    this.SendSMSObjectIdField = value;
                    this.RaisePropertyChanged("SendSMSObjectId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((this.StatusCodeField.Equals(value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int GsmOperator {
            get {
                return this.GsmOperatorField;
            }
            set {
                if ((this.GsmOperatorField.Equals(value) != true)) {
                    this.GsmOperatorField = value;
                    this.RaisePropertyChanged("GsmOperator");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.mikro-odeme.com/", ConfigurationName="SendInformationSMSService.MSendSMSServiceSoap")]
    public interface MSendSMSServiceSoap {
        
        // CODEGEN: Generating message contract since element name token from namespace http://services.mikro-odeme.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://services.mikro-odeme.com/SendSMS", ReplyAction="*")]
        Wirecard.DeveloperPortal.Core.SendInformationSMSService.SendSMSResponse SendSMS(Wirecard.DeveloperPortal.Core.SendInformationSMSService.SendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.mikro-odeme.com/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<Wirecard.DeveloperPortal.Core.SendInformationSMSService.SendSMSResponse> SendSMSAsync(Wirecard.DeveloperPortal.Core.SendInformationSMSService.SendSMSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS", Namespace="http://services.mikro-odeme.com/", Order=0)]
        public Wirecard.DeveloperPortal.Core.SendInformationSMSService.SendSMSRequestBody Body;
        
        public SendSMSRequest() {
        }
        
        public SendSMSRequest(Wirecard.DeveloperPortal.Core.SendInformationSMSService.SendSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.mikro-odeme.com/")]
    public partial class SendSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Wirecard.DeveloperPortal.Core.SendInformationSMSService.MAuthToken token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Wirecard.DeveloperPortal.Core.SendInformationSMSService.MSendSMSInput input;
        
        public SendSMSRequestBody() {
        }
        
        public SendSMSRequestBody(Wirecard.DeveloperPortal.Core.SendInformationSMSService.MAuthToken token, Wirecard.DeveloperPortal.Core.SendInformationSMSService.MSendSMSInput input) {
            this.token = token;
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSResponse", Namespace="http://services.mikro-odeme.com/", Order=0)]
        public Wirecard.DeveloperPortal.Core.SendInformationSMSService.SendSMSResponseBody Body;
        
        public SendSMSResponse() {
        }
        
        public SendSMSResponse(Wirecard.DeveloperPortal.Core.SendInformationSMSService.SendSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.mikro-odeme.com/")]
    public partial class SendSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Wirecard.DeveloperPortal.Core.SendInformationSMSService.MSendSMSOutput SendSMSResult;
        
        public SendSMSResponseBody() {
        }
        
        public SendSMSResponseBody(Wirecard.DeveloperPortal.Core.SendInformationSMSService.MSendSMSOutput SendSMSResult) {
            this.SendSMSResult = SendSMSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MSendSMSServiceSoapChannel : Wirecard.DeveloperPortal.Core.SendInformationSMSService.MSendSMSServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MSendSMSServiceSoapClient : System.ServiceModel.ClientBase<Wirecard.DeveloperPortal.Core.SendInformationSMSService.MSendSMSServiceSoap>, Wirecard.DeveloperPortal.Core.SendInformationSMSService.MSendSMSServiceSoap {
        
        public MSendSMSServiceSoapClient() {
        }
        
        public MSendSMSServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MSendSMSServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MSendSMSServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MSendSMSServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Wirecard.DeveloperPortal.Core.SendInformationSMSService.SendSMSResponse Wirecard.DeveloperPortal.Core.SendInformationSMSService.MSendSMSServiceSoap.SendSMS(Wirecard.DeveloperPortal.Core.SendInformationSMSService.SendSMSRequest request) {
            return base.Channel.SendSMS(request);
        }
        
        public Wirecard.DeveloperPortal.Core.SendInformationSMSService.MSendSMSOutput SendSMS(Wirecard.DeveloperPortal.Core.SendInformationSMSService.MAuthToken token, Wirecard.DeveloperPortal.Core.SendInformationSMSService.MSendSMSInput input) {
            Wirecard.DeveloperPortal.Core.SendInformationSMSService.SendSMSRequest inValue = new Wirecard.DeveloperPortal.Core.SendInformationSMSService.SendSMSRequest();
            inValue.Body = new Wirecard.DeveloperPortal.Core.SendInformationSMSService.SendSMSRequestBody();
            inValue.Body.token = token;
            inValue.Body.input = input;
            Wirecard.DeveloperPortal.Core.SendInformationSMSService.SendSMSResponse retVal = ((Wirecard.DeveloperPortal.Core.SendInformationSMSService.MSendSMSServiceSoap)(this)).SendSMS(inValue);
            return retVal.Body.SendSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wirecard.DeveloperPortal.Core.SendInformationSMSService.SendSMSResponse> Wirecard.DeveloperPortal.Core.SendInformationSMSService.MSendSMSServiceSoap.SendSMSAsync(Wirecard.DeveloperPortal.Core.SendInformationSMSService.SendSMSRequest request) {
            return base.Channel.SendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wirecard.DeveloperPortal.Core.SendInformationSMSService.SendSMSResponse> SendSMSAsync(Wirecard.DeveloperPortal.Core.SendInformationSMSService.MAuthToken token, Wirecard.DeveloperPortal.Core.SendInformationSMSService.MSendSMSInput input) {
            Wirecard.DeveloperPortal.Core.SendInformationSMSService.SendSMSRequest inValue = new Wirecard.DeveloperPortal.Core.SendInformationSMSService.SendSMSRequest();
            inValue.Body = new Wirecard.DeveloperPortal.Core.SendInformationSMSService.SendSMSRequestBody();
            inValue.Body.token = token;
            inValue.Body.input = input;
            return ((Wirecard.DeveloperPortal.Core.SendInformationSMSService.MSendSMSServiceSoap)(this)).SendSMSAsync(inValue);
        }
    }
}
