//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wirecard.DeveloperPortal.Core.SubscriberService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.3pay.com/services/", ConfigurationName="SubscriberService.SubscriberManagementServiceSoap")]
    public interface SubscriberManagementServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/DeactivateSubscriber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Wirecard.DeveloperPortal.Core.SubscriberService.MOperationOutput DeactivateSubscriber(Wirecard.DeveloperPortal.Core.SubscriberService.MAuthToken token, System.Guid subscriberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/DeactivateSubscriber", ReplyAction="*")]
        System.Threading.Tasks.Task<Wirecard.DeveloperPortal.Core.SubscriberService.MOperationOutput> DeactivateSubscriberAsync(Wirecard.DeveloperPortal.Core.SubscriberService.MAuthToken token, System.Guid subscriberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/DeleteSubscriber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Wirecard.DeveloperPortal.Core.SubscriberService.MOperationOutput DeleteSubscriber(Wirecard.DeveloperPortal.Core.SubscriberService.MAuthToken token, System.Guid subscriberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/DeleteSubscriber", ReplyAction="*")]
        System.Threading.Tasks.Task<Wirecard.DeveloperPortal.Core.SubscriberService.MOperationOutput> DeleteSubscriberAsync(Wirecard.DeveloperPortal.Core.SubscriberService.MAuthToken token, System.Guid subscriberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/SelectSubscriber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Wirecard.DeveloperPortal.Core.SubscriberService.MSelectSubscriberOutput SelectSubscriber(Wirecard.DeveloperPortal.Core.SubscriberService.MAuthToken token, Wirecard.DeveloperPortal.Core.SubscriberService.MSelectSubscriberInput input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/SelectSubscriber", ReplyAction="*")]
        System.Threading.Tasks.Task<Wirecard.DeveloperPortal.Core.SubscriberService.MSelectSubscriberOutput> SelectSubscriberAsync(Wirecard.DeveloperPortal.Core.SubscriberService.MAuthToken token, Wirecard.DeveloperPortal.Core.SubscriberService.MSelectSubscriberInput input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/SelectSubscriberDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Wirecard.DeveloperPortal.Core.SubscriberService.MSubscriberDetailOutput SelectSubscriberDetail(Wirecard.DeveloperPortal.Core.SubscriberService.MAuthToken token, System.Guid subscriberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/SelectSubscriberDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<Wirecard.DeveloperPortal.Core.SubscriberService.MSubscriberDetailOutput> SelectSubscriberDetailAsync(Wirecard.DeveloperPortal.Core.SubscriberService.MAuthToken token, System.Guid subscriberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/UpdateSubscriberPriceByIdandDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Wirecard.DeveloperPortal.Core.SubscriberService.MResult UpdateSubscriberPriceByIdandDate(Wirecard.DeveloperPortal.Core.SubscriberService.MAuthToken token, System.Guid serviceSubscriberId, System.DateTime validFrom, double newPrice, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.3pay.com/services/UpdateSubscriberPriceByIdandDate", ReplyAction="*")]
        System.Threading.Tasks.Task<Wirecard.DeveloperPortal.Core.SubscriberService.MResult> UpdateSubscriberPriceByIdandDateAsync(Wirecard.DeveloperPortal.Core.SubscriberService.MAuthToken token, System.Guid serviceSubscriberId, System.DateTime validFrom, double newPrice, string description);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MAuthToken : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userCodeField;
        
        private string pinField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserCode {
            get {
                return this.userCodeField;
            }
            set {
                this.userCodeField = value;
                this.RaisePropertyChanged("UserCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Pin {
            get {
                return this.pinField;
            }
            set {
                this.pinField = value;
                this.RaisePropertyChanged("Pin");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int statusCodeField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MSubscriberPayment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime paymentDateField;
        
        private bool isPaidField;
        
        private System.Guid orderObjectIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime PaymentDate {
            get {
                return this.paymentDateField;
            }
            set {
                this.paymentDateField = value;
                this.RaisePropertyChanged("PaymentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool IsPaid {
            get {
                return this.isPaidField;
            }
            set {
                this.isPaidField = value;
                this.RaisePropertyChanged("IsPaid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Guid OrderObjectId {
            get {
                return this.orderObjectIdField;
            }
            set {
                this.orderObjectIdField = value;
                this.RaisePropertyChanged("OrderObjectId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MSubscriberDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid subscriberIdField;
        
        private string gSMField;
        
        private System.DateTime startDateField;
        
        private int subscriberTypeIdField;
        
        private int paymentCategoryIdField;
        
        private double basePriceField;
        
        private double baseUnitPriceField;
        
        private int productIdField;
        
        private string productNameField;
        
        private int orderChannelIdField;
        
        private System.DateTime lastSuccessfulPaymentDateField;
        
        private int gsmOperatorField;
        
        private bool activeField;
        
        private string cancelKeywordField;
        
        private MSubscriberPayment[] paymentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid SubscriberId {
            get {
                return this.subscriberIdField;
            }
            set {
                this.subscriberIdField = value;
                this.RaisePropertyChanged("SubscriberId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string GSM {
            get {
                return this.gSMField;
            }
            set {
                this.gSMField = value;
                this.RaisePropertyChanged("GSM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("StartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int SubscriberTypeId {
            get {
                return this.subscriberTypeIdField;
            }
            set {
                this.subscriberTypeIdField = value;
                this.RaisePropertyChanged("SubscriberTypeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int PaymentCategoryId {
            get {
                return this.paymentCategoryIdField;
            }
            set {
                this.paymentCategoryIdField = value;
                this.RaisePropertyChanged("PaymentCategoryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double BasePrice {
            get {
                return this.basePriceField;
            }
            set {
                this.basePriceField = value;
                this.RaisePropertyChanged("BasePrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double BaseUnitPrice {
            get {
                return this.baseUnitPriceField;
            }
            set {
                this.baseUnitPriceField = value;
                this.RaisePropertyChanged("BaseUnitPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("ProductId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
                this.RaisePropertyChanged("ProductName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int OrderChannelId {
            get {
                return this.orderChannelIdField;
            }
            set {
                this.orderChannelIdField = value;
                this.RaisePropertyChanged("OrderChannelId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public System.DateTime LastSuccessfulPaymentDate {
            get {
                return this.lastSuccessfulPaymentDateField;
            }
            set {
                this.lastSuccessfulPaymentDateField = value;
                this.RaisePropertyChanged("LastSuccessfulPaymentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int GsmOperator {
            get {
                return this.gsmOperatorField;
            }
            set {
                this.gsmOperatorField = value;
                this.RaisePropertyChanged("GsmOperator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string CancelKeyword {
            get {
                return this.cancelKeywordField;
            }
            set {
                this.cancelKeywordField = value;
                this.RaisePropertyChanged("CancelKeyword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=14)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Payment")]
        public MSubscriberPayment[] Payments {
            get {
                return this.paymentsField;
            }
            set {
                this.paymentsField = value;
                this.RaisePropertyChanged("Payments");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MSubscriberDetailOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int statusCodeField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private MSubscriberDetail subscriberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public MSubscriberDetail Subscriber {
            get {
                return this.subscriberField;
            }
            set {
                this.subscriberField = value;
                this.RaisePropertyChanged("Subscriber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MSubscriber : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid subscriberIdField;
        
        private string gSMField;
        
        private System.DateTime startDateField;
        
        private int subscriberTypeIdField;
        
        private int paymentCategoryIdField;
        
        private double basePriceField;
        
        private double baseUnitPriceField;
        
        private int productIdField;
        
        private string productNameField;
        
        private int orderChannelIdField;
        
        private bool activeField;
        
        private System.DateTime lastSuccessfulPaymentDateField;
        
        private int gsmOperatorField;
        
        private string cancelKeywordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid SubscriberId {
            get {
                return this.subscriberIdField;
            }
            set {
                this.subscriberIdField = value;
                this.RaisePropertyChanged("SubscriberId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string GSM {
            get {
                return this.gSMField;
            }
            set {
                this.gSMField = value;
                this.RaisePropertyChanged("GSM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("StartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int SubscriberTypeId {
            get {
                return this.subscriberTypeIdField;
            }
            set {
                this.subscriberTypeIdField = value;
                this.RaisePropertyChanged("SubscriberTypeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int PaymentCategoryId {
            get {
                return this.paymentCategoryIdField;
            }
            set {
                this.paymentCategoryIdField = value;
                this.RaisePropertyChanged("PaymentCategoryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double BasePrice {
            get {
                return this.basePriceField;
            }
            set {
                this.basePriceField = value;
                this.RaisePropertyChanged("BasePrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double BaseUnitPrice {
            get {
                return this.baseUnitPriceField;
            }
            set {
                this.baseUnitPriceField = value;
                this.RaisePropertyChanged("BaseUnitPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("ProductId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
                this.RaisePropertyChanged("ProductName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int OrderChannelId {
            get {
                return this.orderChannelIdField;
            }
            set {
                this.orderChannelIdField = value;
                this.RaisePropertyChanged("OrderChannelId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.DateTime LastSuccessfulPaymentDate {
            get {
                return this.lastSuccessfulPaymentDateField;
            }
            set {
                this.lastSuccessfulPaymentDateField = value;
                this.RaisePropertyChanged("LastSuccessfulPaymentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int GsmOperator {
            get {
                return this.gsmOperatorField;
            }
            set {
                this.gsmOperatorField = value;
                this.RaisePropertyChanged("GsmOperator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string CancelKeyword {
            get {
                return this.cancelKeywordField;
            }
            set {
                this.cancelKeywordField = value;
                this.RaisePropertyChanged("CancelKeyword");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MSelectSubscriberOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int statusCodeField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private MSubscriber[] subscribersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Subscriber")]
        public MSubscriber[] Subscribers {
            get {
                return this.subscribersField;
            }
            set {
                this.subscribersField = value;
                this.RaisePropertyChanged("Subscribers");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MSelectSubscriberInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int productIdField;
        
        private string gSMField;
        
        private int orderChannelIdField;
        
        private int activeField;
        
        private int subscriberTypeField;
        
        private System.DateTime startDateMinField;
        
        private System.DateTime startDateMaxField;
        
        private System.DateTime lastSuccessfulPaymentDateMinField;
        
        private System.DateTime lastSuccessfulPaymentDateMaxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("ProductId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string GSM {
            get {
                return this.gSMField;
            }
            set {
                this.gSMField = value;
                this.RaisePropertyChanged("GSM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int OrderChannelId {
            get {
                return this.orderChannelIdField;
            }
            set {
                this.orderChannelIdField = value;
                this.RaisePropertyChanged("OrderChannelId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int SubscriberType {
            get {
                return this.subscriberTypeField;
            }
            set {
                this.subscriberTypeField = value;
                this.RaisePropertyChanged("SubscriberType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime StartDateMin {
            get {
                return this.startDateMinField;
            }
            set {
                this.startDateMinField = value;
                this.RaisePropertyChanged("StartDateMin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime StartDateMax {
            get {
                return this.startDateMaxField;
            }
            set {
                this.startDateMaxField = value;
                this.RaisePropertyChanged("StartDateMax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime LastSuccessfulPaymentDateMin {
            get {
                return this.lastSuccessfulPaymentDateMinField;
            }
            set {
                this.lastSuccessfulPaymentDateMinField = value;
                this.RaisePropertyChanged("LastSuccessfulPaymentDateMin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime LastSuccessfulPaymentDateMax {
            get {
                return this.lastSuccessfulPaymentDateMaxField;
            }
            set {
                this.lastSuccessfulPaymentDateMaxField = value;
                this.RaisePropertyChanged("LastSuccessfulPaymentDateMax");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.3pay.com/services/")]
    public partial class MOperationOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int statusCodeField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SubscriberManagementServiceSoapChannel : Wirecard.DeveloperPortal.Core.SubscriberService.SubscriberManagementServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubscriberManagementServiceSoapClient : System.ServiceModel.ClientBase<Wirecard.DeveloperPortal.Core.SubscriberService.SubscriberManagementServiceSoap>, Wirecard.DeveloperPortal.Core.SubscriberService.SubscriberManagementServiceSoap {
        
        public SubscriberManagementServiceSoapClient() {
        }
        
        public SubscriberManagementServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubscriberManagementServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubscriberManagementServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubscriberManagementServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wirecard.DeveloperPortal.Core.SubscriberService.MOperationOutput DeactivateSubscriber(Wirecard.DeveloperPortal.Core.SubscriberService.MAuthToken token, System.Guid subscriberId) {
            return base.Channel.DeactivateSubscriber(token, subscriberId);
        }
        
        public System.Threading.Tasks.Task<Wirecard.DeveloperPortal.Core.SubscriberService.MOperationOutput> DeactivateSubscriberAsync(Wirecard.DeveloperPortal.Core.SubscriberService.MAuthToken token, System.Guid subscriberId) {
            return base.Channel.DeactivateSubscriberAsync(token, subscriberId);
        }
        
        public Wirecard.DeveloperPortal.Core.SubscriberService.MOperationOutput DeleteSubscriber(Wirecard.DeveloperPortal.Core.SubscriberService.MAuthToken token, System.Guid subscriberId) {
            return base.Channel.DeleteSubscriber(token, subscriberId);
        }
        
        public System.Threading.Tasks.Task<Wirecard.DeveloperPortal.Core.SubscriberService.MOperationOutput> DeleteSubscriberAsync(Wirecard.DeveloperPortal.Core.SubscriberService.MAuthToken token, System.Guid subscriberId) {
            return base.Channel.DeleteSubscriberAsync(token, subscriberId);
        }
        
        public Wirecard.DeveloperPortal.Core.SubscriberService.MSelectSubscriberOutput SelectSubscriber(Wirecard.DeveloperPortal.Core.SubscriberService.MAuthToken token, Wirecard.DeveloperPortal.Core.SubscriberService.MSelectSubscriberInput input) {
            return base.Channel.SelectSubscriber(token, input);
        }
        
        public System.Threading.Tasks.Task<Wirecard.DeveloperPortal.Core.SubscriberService.MSelectSubscriberOutput> SelectSubscriberAsync(Wirecard.DeveloperPortal.Core.SubscriberService.MAuthToken token, Wirecard.DeveloperPortal.Core.SubscriberService.MSelectSubscriberInput input) {
            return base.Channel.SelectSubscriberAsync(token, input);
        }
        
        public Wirecard.DeveloperPortal.Core.SubscriberService.MSubscriberDetailOutput SelectSubscriberDetail(Wirecard.DeveloperPortal.Core.SubscriberService.MAuthToken token, System.Guid subscriberId) {
            return base.Channel.SelectSubscriberDetail(token, subscriberId);
        }
        
        public System.Threading.Tasks.Task<Wirecard.DeveloperPortal.Core.SubscriberService.MSubscriberDetailOutput> SelectSubscriberDetailAsync(Wirecard.DeveloperPortal.Core.SubscriberService.MAuthToken token, System.Guid subscriberId) {
            return base.Channel.SelectSubscriberDetailAsync(token, subscriberId);
        }
        
        public Wirecard.DeveloperPortal.Core.SubscriberService.MResult UpdateSubscriberPriceByIdandDate(Wirecard.DeveloperPortal.Core.SubscriberService.MAuthToken token, System.Guid serviceSubscriberId, System.DateTime validFrom, double newPrice, string description) {
            return base.Channel.UpdateSubscriberPriceByIdandDate(token, serviceSubscriberId, validFrom, newPrice, description);
        }
        
        public System.Threading.Tasks.Task<Wirecard.DeveloperPortal.Core.SubscriberService.MResult> UpdateSubscriberPriceByIdandDateAsync(Wirecard.DeveloperPortal.Core.SubscriberService.MAuthToken token, System.Guid serviceSubscriberId, System.DateTime validFrom, double newPrice, string description) {
            return base.Channel.UpdateSubscriberPriceByIdandDateAsync(token, serviceSubscriberId, validFrom, newPrice, description);
        }
    }
}
